<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Budget Report - {{ $currentProject->name }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 10px;
        }
        .project-title {
            font-size: 18px;
            font-weight: bold;
            color: #1e40af;
        }
        .report-date {
            font-size: 12px;
            color: #6b7280;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        .table th {
            background-color: #3b82f6;
            color: white;
            text-align: left;
            padding: 8px;
            font-weight: bold;
        }
        .table td {
            padding: 8px;
            border-bottom: 1px solid #e5e7eb;
        }
        .table tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .total-row {
            font-weight: bold;
            background-color: #e5e7eb !important;
        }
        .status-approved {
            color: #10b981;
            font-weight: bold;
        }
        .status-pending {
            color: #f59e0b;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 10px;
            color: #6b7280;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
        }
        .group-header {
            background-color: #e5e7eb;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="project-title">{{ $currentProject->name }} - Budget Report</div>
        <div class="report-date">Generated on: {{ now()->format('F j, Y') }}</div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Budget Name</th>
                <th>Description</th>
                <th>Phase/Milestone</th>
                <th>Estimated Amount</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @php
                $totalAmount = 0;
            @endphp

            @foreach($budgets as $budget)
                <tr>
                    <td>{{ $budget->budget_name }}</td>
                    <td>{{ Str::limit($budget->description, 50) }}</td>
                    <td>
                        @if($budget->phase)
                            Phase: {{ $budget->phase->name }}
                        @elseif($budget->milestone)
                            Milestone: {{ $budget->milestone->name }}
                        @else
                            N/A
                        @endif
                    </td>
                    <td>
                        @if($budget->estimated_amount)
                            {{ number_format($budget->estimated_amount, 2) }}
                            @php $totalAmount += $budget->estimated_amount; @endphp
                        @else
                            N/A
                        @endif
                    </td>
                    <td class="{{ $budget->approved ? 'status-approved' : 'status-pending' }}">
                        {{ $budget->approved ? 'Approved' : 'Pending' }}
                    </td>
                </tr>
            @endforeach

            <tr class="total-row">
                <td colspan="3">Total</td>
                <td>{{ number_format($totalAmount, 2) }}</td>
                <td></td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        Page 1 of 1 | Generated by {{ auth()->user()->name }}
    </div>
</body>
</html>